kind: pipeline
type: docker
name: default

volumes:
- name: shared
  temp: {}

steps:
- name: generate documentation
  image: python:3.11
  volumes:
    - name: shared
      path: /shared
  commands:
    - pip install pydoc-markdown
    - pip install -r requirements.txt
    - python generate_docs.py
    - git add docs/*
    - git commit -m "Update documentation" -a || echo "No changes to commit"

- name: run tests
  image: python:3.11
  volumes:
    - name: shared
      path: /shared
  commands:
    - CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
    - |
      if echo "${CHANGED_FILES}" | grep -qE "tests/.*\.py|src/.*\.py"; then
        pip install pytest-md
        pip install -r requirements.txt
        pytest --md report.md
        mv report.md docs/tests_report.md
        git add docs/tests_report.md
        git commit -m "Update test report" -a || echo "No changes to test report"
      fi

# - name: build docker container
#   image: gcr.io/kaniko-project/executor:debug
#   volumes:
#     - name: docker_config
#       path: /kaniko/.docker/
#   depends_on:
#     - run tests
#   commands:
#     - mkdir -p /kaniko/.docker/
#     - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(echo -n $DOCKER_USERNAME:$DOCKER_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
#     - VERSION=$(grep 'ENV VERSION' Dockerfile | cut -d '=' -f 2)
#     - |
#       if [ "${DRONE_BRANCH}" = "dev" ]; then
#         VERSION="dev${VERSION}"
#       fi
#     - /kaniko/executor --context $PWD --dockerfile $PWD/Dockerfile --destination mullinmax/purrs:$VERSION --volume /kaniko/.docker:/kaniko/.docker

- name: build docker container
  image: plugins/kaniko
  depends_on:
    - run tests
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: mullinmax/purrs
    tags: latest
  when:
    branch:
      - main


- name: push to gitea
  image: alpine/git
  volumes:
    - name: shared
      path: /shared
  depends_on:
    - generate documentation
    - run tests
  environment:
    SSH_KEY:
      from_secret: GITEA_SSH_KEY
  commands:
    - mkdir /root/.ssh/
    - 'echo -n "$SSH_KEY" | base64 -d > /root/.ssh/id_rsa'
    - 'chmod 600 /root/.ssh/id_rsa'
    - 'ssh-keyscan -p 2222 -t rsa gitea.doze.dev >> /root/.ssh/known_hosts'
    - git config --global user.email "mullinmax@gmail.com"
    - git config --global user.name "Maxwell Mullin"
    - git remote set-url origin ssh://git@gitea.doze.dev:2222/maxwell/purrs.git
    - git push origin HEAD

trigger:
  branch:
    - dev
    - main
  event:
    - push
