kind: pipeline
type: docker
name: default

steps:
- name: generate docs
  image: python:3.11
  commands:
    - pip install pydoc-markdown
    - pip install -r requirements.txt
    - pydoc-markdown -I src -O docs
    - git add docs/*
    - git commit -m "Update documentation" -a || echo "No changes to commit"
- name: push to gitea
  image: alpine/git
  environment:
    SSH_KEY:
      from_secret: GITEA_SSH_KEY
  commands:
    - mkdir /root/.ssh/
    - 'echo -n "$SSH_KEY" | base64 -d > /root/.ssh/id_rsa'
    - 'chmod 600 /root/.ssh/id_rsa'
    - 'ssh-keyscan -p 2222 -t rsa gitea.doze.dev >> /root/.ssh/known_hosts'
    - git config --global user.email "mullinmax@gmail.com"
    - git config --global user.name "Maxwell Mullin"
    - git remote set-url origin ssh://git@gitea.doze.dev:2222/maxwell/purrs.git
    - git push origin HEAD

trigger:
  branch:
    - dev
  event:
    - push
