kind: pipeline
type: docker
name: default

volumes:
- name: shared
  temp: {}

steps:
- name: get version
  image: alpine
  volumes:
    - name: shared
      path: /shared
  commands:
    - version=$(grep 'ENV VERSION' Dockerfile | cut -d '=' -f2)
    - echo $version > /shared/.version

- name: generate tags
  image: alpine
  volumes:
    - name: shared
      path: /shared
  commands:
    - |
      if [ "${DRONE_BRANCH}" = "main" ]; then
        echo -e "latest\n$(cat /shared/.version)" > /shared/.tags
      else
        echo "dev${DRONE_BUILD_NUMBER}" > /shared/.tags
      fi

- name: generate documentation
  image: python:3.11
  volumes:
    - name: shared
      path: /shared
  commands:
    - pip install pydoc-markdown
    - pip install -r requirements.txt
    - python generate_docs.py
    - git add docs/*
    - git commit -m "Update documentation" -a || echo "No changes to commit"

- name: run tests
  image: python:3.11
  volumes:
    - name: shared
      path: /shared
  commands:
    - CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
    - |
      if echo "${CHANGED_FILES}" | grep -qE "tests/.*\.py|src/.*\.py"; then
        pip install pytest-md
        pip install -r requirements.txt
        pytest --md report.md
        mv report.md docs/tests_report.md
        git add docs/tests_report.md
        git commit -m "Update test report" -a || echo "No changes to test report"
      fi

- name: build docker container
  image: plugins/kaniko
  volumes:
    - name: shared
      path: /shared
  depends_on:
    - run tests
    - get version
    - generate tags
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: mullinmax/purrs
    tags: 
      from_file: /shared/.tags
  when:
    branch:
      - main
      - dev

- name: push to gitea
  image: alpine/git
  volumes:
    - name: shared
      path: /shared
  depends_on:
    - generate documentation
    - run tests
  environment:
    SSH_KEY:
      from_secret: GITEA_SSH_KEY
  commands:
    - mkdir /root/.ssh/
    - 'echo -n "$SSH_KEY" | base64 -d > /root/.ssh/id_rsa'
    - 'chmod 600 /root/.ssh/id_rsa'
    - 'ssh-keyscan -p 2222 -t rsa gitea.doze.dev >> /root/.ssh/known_hosts'
    - git config --global user.email "mullinmax@gmail.com"
    - git config --global user.name "Maxwell Mullin"
    - git remote set-url origin ssh://git@gitea.doze.dev:2222/maxwell/purrs.git
    - git push origin HEAD

trigger:
  branch:
    - dev
    - main
  event:
    - push
