kind: pipeline
name: generate_docs

trigger:
  event:
    - push
  branch:
    - main

steps:
  - name: generate_docs
    pull: if-not-exists
    image: python:3.11
    commands:
      - pip install -r requirements.txt  # Install necessary dependencies for generating docs
      - pip install pdoc3
      - cd src  # Move to the directory containing the source files
      - pdoc --html --output-dir ../docs .  # Generate the Markdown documentation using pdoc3

  - name: push_docs_to_wiki
    image: alpine/git
    environment:
      SSH_PRIVATE_KEY:
        from_secret: GITEA_SSH_PRIVATE_KEY
    commands:
      - apk add --no-cache openssh-client
      - eval $(ssh-agent -s)
      - echo "$SSH_PRIVATE_KEY" | ssh-add -
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - ssh-keyscan -H <your_gitea_instance> >> ~/.ssh/known_hosts
      - git clone --depth 1 --branch master git@<your_gitea_instance>:path/to/your/repository.wiki.git docs
      - cd docs
      - git config user.name "Drone CI"
      - git config user.email "drone@ci.com"
      - rm -rf *
      - cp -r ../docs/* .
      - git add .
      - git commit -m "Update documentation"
      - git push origin master
