version: 21
jobs:
- name: Pull Request Review
  jobExecutor: docker-executor
  steps:
  - !UseTemplateStep
    name: Checkout Code and Set Build Version
    templateName: Checkout Code and Set Build Version
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !UseTemplateStep
    name: Execute Tests
    templateName: Execute Tests
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !UseTemplateStep
    name: Trial Docker Container Build
    templateName: Trial Docker Container Build
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !PullRequestUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Update Master or Dev
  jobExecutor: docker-executor
  steps:
  - !UseTemplateStep
    name: Checkout Code and Set Build Version
    templateName: Checkout Code and Set Build Version
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !UseTemplateStep
    name: Execute Tests
    templateName: Execute Tests
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !UseTemplateStep
    name: Push Docker Container to DockerHub
    templateName: Push Docker Container to Dockerhub
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !UseTemplateStep
    name: Sync master to Github
    templateName: Sync to GitHub
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: master dev main
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
stepTemplates:
- name: Checkout Code and Set Build Version
  steps:
  - !CheckoutStep
    name: Checkout Code
    cloneCredential: !DefaultCredential {}
    withLfs: true
    withSubmodules: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Write Build Version to file:BUILD_VERSION
    runInContainer: true
    image: python:3.11
    interpreter: !DefaultInterpreter
      commands:
      - PACKAGE_VERSION="$(grep "VERSION" Dockerfile | cut -d '=' -f 2)"
      - BUILD_NUMBER="@build_number@"
      - CURRENT_BRANCH=$(git branch --show-current)
      - ''
      - if [ -z "$PACKAGE_VERSION" ]; then
      - '    echo "Error: Failed to extract PACKAGE_VERSION from Dockerfile"'
      - '    exit 1'
      - fi
      - ''
      - if [ "$CURRENT_BRANCH" != "master" ] && [ "$CURRENT_BRANCH" != "main" ]; then
      - "\texport BUILD_VERSION=\"${PACKAGE_VERSION}.${CURRENT_BRANCH}.dev${BUILD_NUMBER}\""
      - "  \techo \"$BUILD_VERSION\" > BUILD_VERSION"
      - "\techo \"$BUILD_NUMBER\""
      - "\techo \"$BUILD_VERSION\""
      - else
      - "\texport BUILD_VERSION=\"${PACKAGE_VERSION}\""
      - "  \techo \"$BUILD_VERSION\" > BUILD_VERSION"
      - "\techo \"$BUILD_VERSION\""
      - fi
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Write Project Name to File:PROJECT_NAME
    runInContainer: true
    image: python:3.11
    interpreter: !DefaultInterpreter
      commands:
      - grep "NAME" Dockerfile | cut -d '=' -f 2 > PROJECT_NAME
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !SetBuildVersionStep
    name: Set Build Version
    buildVersion: '@file:BUILD_VERSION@'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
- name: Execute Tests
  steps:
  - !CommandStep
    name: Run Pytest
    runInContainer: true
    image: python:3.11
    interpreter: !DefaultInterpreter
      commands:
      - pip install -e .[test]
      - pytest
      - ruff check . --fix
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
- name: Trial Docker Container Build
  steps:
  - !BuildImageStep
    name: Build Docker Container
    tags: '@build_version@'
    publish: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
- name: Push Docker Container to Dockerhub
  steps:
  - !CommandStep
    name: Publish to DockerHub
    runInContainer: true
    image: docker
    interpreter: !DefaultInterpreter
      commands:
      - dockerhub_user=@secret:dockerhub_user@
      - build_version=@build_version@
      - '# wrapped in quotes to prevent issues with $ in passwords'
      - echo '@secrets:dockerhub_password@' | docker login -u $dockerhub_user --password-stdin
      - docker build -t $dockerhub_user/@file:PROJECT_NAME@:$build_version -t $dockerhub_user/@file:PROJECT_NAME@:latest
        .
      - docker push --all-tags $dockerhub_user/@project_name@
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
- name: Sync to GitHub
  steps:
  - !CommandStep
    name: Sync master to GitHub
    runInContainer: true
    image: alpine/git:1.0.7
    interpreter: !DefaultInterpreter
      commands:
      - '#git config --global --unset http.extraHeader'
      - '#gh_user=@secrets:github_user@'
      - '#gh_token=@secrets:github_token@'
      - '#git push -f https://$gh_user:$gh_token@@github.com/$gh_user/@project_name@.git
        HEAD:main'
      - '#git push -f https://github.com/$gh_user/@project_name@.git HEAD:main'
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PushRepository
    name: Sync to Github
    remoteUrl: https://github.com/@secret:github_user@/@file:PROJECT_NAME@.git
    passwordSecret: github_token
    force: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
